name: Alnitak_Flutter_Build

on:
  push:
    branches: [ main, master ] # 当你提交代码时触发
  workflow_dispatch: # 允许你手动点击按钮触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # 如果你的项目比较旧，可以尝试指定版本 3.19.0
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK
        # 使用 --no-tree-shake-icons 防止因为缺少字体图标导致编译失败
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Alnitak-Release-App
          path: build/app/outputs/flutter-apk/app-release.apk
